name: Staging

on:
  push:
    branches:
      - staging

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    uses: redpanda/workflows/.github/workflows/main.yml@main
    with:
      file: file.json
